### ISSUE TITLE
Incompatible with stylelint v16.2.1

### ISSUE THREAD

**Issue by beckerjohannes** [JulianSSS/stylelint-no-magic-numbers#20]
**Describe the bug**
After updating from stylelint 15.11.0 to 16.2.1 i get the following error (see Error Logs).
Switching back and it runs again.

**To Reproduce**
Already mentioned in description. Try to run with 16.2.1. 
**Expected behavior**
Should work with current stylelint version.

**Error Logs**
```shell
Error: Cannot find module '...\frontend\node_modules\stylelint\lib\utils\isVariable'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (...\frontend\node_modules\stylelint-magic-numbers\dist\index.js:10:42)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version 20.11.0
 - Package Manager npm 10.2.4

**Additional context**

**Comment by JuStTheDev** [comment]
Thank you for this information @beckerjohannes! I will take care of that issue soon. After a quick look I found a bunch of places that need to be improved for migrating to stylelint 16.

**Comment by JuStTheDev** [comment]
Hi @beckerjohannes, with Release v2.0.1 of yesterday, there is now a version supporting Stylelint >=16.

**Comment by beckerjohannes** [comment]
@JuStTheDev Thank you very much.
